/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import pojos.*

rule "Chest pain 1"
    dialect "java"
    when
        p : Patient( p.getCondition().isChestPain() == true )
    then
       p.getDisease().setMyocardialInfarction(p.getDisease().getMyocardialInfarction() + 0.5);
        System.out.println("Rule 1 Chest Pain applied over " + p);
        //System.out.println("myocardial infarction: " + p.getDisease().getMyocardialInfarction());
end