/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import pojos.*

rule "Chest pain 1"
    dialect "java"
    when
        p : Patient( p.getConditions().isChestPain() == true )
    then
        p.getDisease().setMyocardialInfarction(p.getDisease().getMyocardialInfarction() + 0.5);
        //System.out.println("Rule 1 Chest Pain applied over " + p);
        //System.out.println("R1 - Myocardial Infarction: " + p.getDisease().getMyocardialInfarction());
end

rule "Chest pain 2"
    dialect "java"
    when
        p : Patient( p.getConditions().isChestPain() == true )
    then
        p.getDisease().setHeartFailure(p.getDisease().getHeartFailure() + 0.3);
        //System.out.println("Rule 2 Chest Pain applied over " + p);
        //System.out.println("R2 - Heart Failure: " + p.getDisease().getHeartFailure());
end

rule "Chest pain 3"
    dialect "java"
    when
        p : Patient( p.getConditions().isChestPain() == true )
    then
        p.getDisease().setpArterialDisease(p.getDisease().getpArterialDisease() + 0.3);
        //System.out.println("Rule 3 Chest Pain applied over " + p);
        //System.out.println("R3 - Peripheral Arterial Disease: " + p.getDisease().getpArterialDisease());
end

rule "Chest pain 4"
    dialect "java"
    when
        p : Patient( p.getConditions().isChestPain() == true )
    then
        p.getDisease().setHeartBurn(p.getDisease().getHeartBurn() + 0.3);
        //System.out.println("Rule 4 Chest Pain applied over " + p);
        //System.out.println("R4 - Heart Burn: " + p.getDisease().getHeartBurn());
end

rule "Chest pain 5"
    dialect "java"
    when
        p : Patient( p.getConditions().isChestPain() == true )
    then
        p.getDisease().setStroke(p.getDisease().getStroke() + 0.2);
        //System.out.println("Rule 5 Chest Pain applied over " + p);
        //System.out.println("R5 - Stroke: " + p.getDisease().getStroke());
end

rule "Chest pain 6"
    dialect "java"
    when
        p : Patient( p.getConditions().isChestPain() == true )
    then
        p.getDisease().setArrythmia(p.getDisease().getArrythmia() + 0.2);
        //System.out.println("Rule 6 Chest Pain applied over " + p);
        //System.out.println("R6 - Arrythmia: " + p.getDisease().getArrythmia());
end

rule "Shortness Of Breath 7"
    dialect "java"
    when
        p : Patient( p.getConditions().isShortnessOfBreath() == true )
    then
        p.getDisease().setMyocardialInfarction(p.getDisease().getMyocardialInfarction() + 0.3);
        //System.out.println("Rule 7 Shortness Of Breath applied over " + p);
        //System.out.println("R7 - Myocardial Infarction: " + p.getDisease().getMyocardialInfarction());
end

rule "Shortness Of Breath 8"
    dialect "java"
    when
        p : Patient( p.getConditions().isShortnessOfBreath() == true )
    then
        p.getDisease().setHeartFailure(p.getDisease().getHeartFailure() + 0.2);
        //System.out.println("Rule 8 Shortness Of Breath applied over " + p);
        //System.out.println("R8 - Heart Failure: " + p.getDisease().getHeartFailure());
end

rule "Shortness Of Breath 9"
    dialect "java"
    when
        p : Patient( p.getConditions().isShortnessOfBreath() == true )
    then
        p.getDisease().setHeartBurn(p.getDisease().getHeartBurn() + 0.4);
        //System.out.println("Rule 9 Shortness Of Breath applied over " + p);
        //System.out.println("R9 - Heart Burn: " + p.getDisease().getHeartBurn());
end

rule "Shortness Of Breath 10"
    dialect "java"
    when
        p : Patient( p.getConditions().isShortnessOfBreath() == true )
    then
        p.getDisease().setStroke(p.getDisease().getStroke() + 0.1);
        //System.out.println("Rule 10 Shortness Of Breath applied over " + p);
        //System.out.println("R10 - Stroke: " + p.getDisease().getStroke());
end

rule "Shortness Of Breath 11"
    dialect "java"
    when
        p : Patient( p.getConditions().isShortnessOfBreath() == true )
    then
        p.getDisease().setArrythmia(p.getDisease().getArrythmia() + 0.2);
        //System.out.println("Rule 11 Shortness Of Breath applied over " + p);
        //System.out.println("R11 - Arrythmia: " + p.getDisease().getArrythmia());
end

rule "Sweating 12"
    dialect "java"
    when
        p : Patient( p.getConditions().isSweating() == true )
    then
        p.getDisease().setMyocardialInfarction(p.getDisease().getMyocardialInfarction() + 0.1);
        //System.out.println("Rule 12 Shortness Of Breath applied over " + p);
        //System.out.println("R12 - Myocardial Infarction: " + p.getDisease().getMyocardialInfarction());
end

rule "Nausea 13"
    dialect "java"
    when
        p : Patient( p.getConditions().isNausea() == true )
    then
        p.getDisease().setMyocardialInfarction(p.getDisease().getMyocardialInfarction() + 0.1);
        //System.out.println("Rule 13 Nausea applied over " + p);
        //System.out.println("R13 - Myocardial Infarction: " + p.getDisease().getMyocardialInfarction());
end

rule "Swelling In Legs 14"
    dialect "java"
    when
        p : Patient( p.getConditions().isSwellingLegs() == true )
    then
        p.getDisease().setHeartFailure(p.getDisease().getHeartFailure() + 0.4);
        //System.out.println("Rule 14 Swelling In Legs " + p);
        //System.out.println("R14 - Heart Failure: " + p.getDisease().getHeartFailure());
end

rule "Fatigue 15"
    dialect "java"
    when
        p : Patient( p.getConditions().isFatigue() == true )
    then
        p.getDisease().setHeartFailure(p.getDisease().getHeartFailure() + 0.1);
        //System.out.println("Rule 15 Fatigue " + p);
        //System.out.println("R15 - Heart Failure: " + p.getDisease().getHeartFailure());
end

rule "Fatigue 16"
    dialect "java"
    when
        p : Patient( p.getConditions().isFatigue() == true )
    then
        p.getDisease().setHeartBurn(p.getDisease().getHeartBurn() + 0.1);
        //System.out.println("Rule 16 Fatigue " + p);
        //System.out.println("R16 - Heart Burn: " + p.getDisease().getHeartBurn());
end

rule "Fatigue 17"
    dialect "java"
    when
        p : Patient( p.getConditions().isFatigue() == true )
    then
        p.getDisease().setHypertension(p.getDisease().getHypertension() + 0.1);
        //System.out.println("Rule 17 Fatigue " + p);
        //System.out.println("R17 - Hypertension: " + p.getDisease().getHypertension());
end

rule "Fatigue 18"
    dialect "java"
    when
        p : Patient( p.getConditions().isFatigue() == true )
    then
        p.getDisease().setArrythmia(p.getDisease().getArrythmia() + 0.1);
        //System.out.println("Rule 18 Fatigue " + p);
        //System.out.println("R18 - Arrythmia: " + p.getDisease().getArrythmia());
end

rule "Legs Pain 19"
    dialect "java"
    when
        p : Patient( p.getConditions().isLegsPain() == true )
    then
        p.getDisease().setpArterialDisease(p.getDisease().getpArterialDisease() + 0.3);
        //System.out.println("Rule 19 Legs Pain " + p);
        //System.out.println("R19 - Peripheral Arterial Disease: " + p.getDisease().getpArterialDisease());
end

rule "Skin Changes 20"
    dialect "java"
    when
        p : Patient( p.getConditions().isSkinChanges() == true )
    then
        p.getDisease().setpArterialDisease(p.getDisease().getpArterialDisease() + 0.1);
        //System.out.println("Rule 20 Skin Changes " + p);
        //System.out.println("R20 - Peripheral Arterial Disease: " + p.getDisease().getpArterialDisease());
end

rule "Temperature Changes 21"
    dialect "java"
    when
        p : Patient( p.getConditions().isTemperatureChanges() == true )
    then
        p.getDisease().setpArterialDisease(p.getDisease().getpArterialDisease() + 0.1);
        //System.out.println("Rule 21 Temperature Changes " + p);
        //System.out.println("R21 - Peripheral Arterial Disease: " + p.getDisease().getpArterialDisease());
end

rule "Temperature Changes 22"
    dialect "java"
    when
        p : Patient( p.getConditions().isTemperatureChanges() == true )
    then
        p.getDisease().setHypertension(p.getDisease().getHypertension() + 0.1);
        //System.out.println("Rule 22 Temperature Changes " + p);
        //System.out.println("R22 - Hypertension: " + p.getDisease().getHypertension());
end

rule "Decreased Pulse 23"
    dialect "java"
    when
        p : Patient( p.getConditions().isDecreasedPulse() == true )
    then
        p.getDisease().setpArterialDisease(p.getDisease().getpArterialDisease() + 0.2);
        //System.out.println("Rule 23 Decreased Pulse " + p);
        //System.out.println("R23 - Peripheral Arterial Disease: " + p.getDisease().getpArterialDisease());
end

rule "Increased Pulse 24"
    dialect "java"
    when
        p : Patient( p.getConditions().isIncreasedPulse() == true )
    then
        p.getDisease().setHeartBurn(p.getDisease().getHeartBurn() + 0.2);
        //System.out.println("Rule 24 Increased Pulse " + p);
        //System.out.println("R24 - Heart Burn: " + p.getDisease().getHeartBurn());
end

rule "High Blood Pressure 25"
    dialect "java"
    when
        p : Patient( p.getConditions().isHighBloodPressure() == true )
    then
        p.getDisease().setHypertension(p.getDisease().getHypertension() + 0.4);
        //System.out.println("Rule 25 High Blood Pressure " + p);
        //System.out.println("R25 - Hypertension: " + p.getDisease().getHypertension());
end

rule "Irregular Heart Beat 26"
    dialect "java"
    when
        p : Patient( p.getConditions().isIrregularHeartBeat() == true )
    then
        p.getDisease().setArrythmia(p.getDisease().getArrythmia() + 0.5);
        //System.out.println("Rule 26 Irregular Heart Beat " + p);
        //System.out.println("R26 - Arrythmia: " + p.getDisease().getArrythmia());
end

rule "Headache 27"
    dialect "java"
    when
        p : Patient( p.getConditions().isHeadache() == true )
    then
        p.getDisease().setHypertension(p.getDisease().getHypertension() + 0.2);
        //System.out.println("Rule 27 Hypertension " + p);
        //System.out.println("R27 - Hypertension: " + p.getDisease().getHypertension());
end

rule "Dizziness 28"
    dialect "java"
    when
        p : Patient( p.getConditions().isDizziness() == true )
    then
        p.getDisease().setHypertension(p.getDisease().getHypertension() + 0.1);
        //System.out.println("Rule 28 Hypertension " + p);
        //System.out.println("R28 - Hypertension: " + p.getDisease().getHypertension());
end

rule "Upper Body Pain 29"
    dialect "java"
    when
        p : Patient( p.getConditions().isUpperBodyPain() == true )
    then
        p.getDisease().setStroke(p.getDisease().getStroke() + 0.5);
        //System.out.println("Rule 29 Stroke " + p);
        //System.out.println("R29 - Stroke: " + p.getDisease().getStroke());
end

rule "Weakness 30"
    dialect "java"
    when
        p : Patient( p.getConditions().isWeakness() == true )
    then
        p.getDisease().setHypertension(p.getDisease().getHypertension() + 0.1);
        //System.out.println("Rule 30 Hypertension " + p);
        //System.out.println("R30 - Hypertension: " + p.getDisease().getHypertension());
end

rule "Weakness 31"
    dialect "java"
    when
        p : Patient( p.getConditions().isWeakness() == true )
    then
        p.getDisease().setStroke(p.getDisease().getStroke() + 0.2);
        //System.out.println("Rule 31 Stroke " + p);
        //System.out.println("R31 - Stroke: " + p.getDisease().getStroke());
end

rule "Constraint Arrythmia - Irregular Heart Beat 32"
    dialect "java"
    when
        p : Patient( p.getConditions().isIrregularHeartBeat() == false )
    then
        p.getDisease().setArrythmia(0);
        //System.out.println("Rule 32 Arrythmia (constraint) " + p);
        //System.out.println("R32 - Arrythmia (constraint): " + p.getDisease().getArrythmia());
end

rule "Constraint Myocardial Infarction - Chest Pain 33"
    dialect "java"
    when
        p : Patient( p.getConditions().isChestPain() == false )
    then
        p.getDisease().setMyocardialInfarction(0);
        //System.out.println("Rule 33 Myocardial Infarction (constraint) " + p);
        //System.out.println("R33 - Myocardial Infarction (constraint): " + p.getDisease().getMyocardialInfarction());
end

rule "Constraint Heart Failure - Swelling Legs 34"
    dialect "java"
    when
        p : Patient( p.getConditions().isSwellingLegs() == false )
    then
        p.getDisease().setHeartFailure(0);
        //System.out.println("Rule 34 Heart Failure (constraint) " + p);
        //System.out.println("R34 - Heart Failure (constraint): " + p.getDisease().getHeartFailure());
end